"""empty message

Revision ID: 5044ea5756e6
Revises: e9167334d9ee
Create Date: 2026-01-12 14:50:22.774823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5044ea5756e6'
down_revision = 'e9167334d9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.Enum('efectivo', 'tarjeta', 'transferencia', 'zelle', 'otro', name='payment_method_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'pagado', 'anulado', 'reembolsado', name='payment_status_enum', native_enum=False), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['usuarios.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
