"""add barber profile fields

Revision ID: fa4edbeccfe0
Revises: 1b785c7d8ac0
Create Date: 2026-01-06 15:24:52.347898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4edbeccfe0'
down_revision = '1b785c7d8ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specialties', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('specialties')
        batch_op.drop_column('bio')
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
